# Generated by Django 5.2.7 on 2025-11-29 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_tasklist_homemaker_maintenance_homemakers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='daily',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
