# Generated by Django 5.2.7 on 2025-11-16 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_remove_users_avatar_url_users_avatar_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_added', to='user.users')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.household')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_bought', to='user.users')),
            ],
            options={
                'indexes': [models.Index(fields=['household', 'is_purchased', 'created_at'], name='shopping_sh_househo_81a143_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_purchased', False)), fields=('household', 'item_name', 'is_purchased'), name='uniq_active_item_per_household')],
            },
        ),
    ]
