# Generated by Django 5.2.7 on 2025-11-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0001_initial'),
        ('user', '0008_remove_users_avatar_url_users_avatar_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('daily', '日用品'), ('hygiene', '衛生用品'), ('kitchen', 'キッチン用品'), ('cleaning', '掃除用品'), ('laundry', '洗濯用品')], max_length=16)),
                ('stock_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('period_days', models.PositiveIntegerField(choices=[(10, '10日'), (20, '20日'), (30, '30日'), (40, '40日'), (50, '50日'), (60, '60日')])),
                ('purchase_date', models.DateField()),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='user.household')),
                ('open_shopping_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_stock', to='shopping.shoppingitem')),
            ],
        ),
    ]
