# Generated by Django 5.2.7 on 2025-11-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='enqueued_to_shopping',
            field=models.BooleanField(default=False),
        ),
    ]
