# Generated by Django 5.2.7 on 2025-11-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_remove_users_avatar_url_users_avatar_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_appliance', models.BooleanField(default=True)),
                ('target_name', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('6m', '半年'), ('12m', '年1'), ('24m', '年2')], max_length=3)),
                ('last_date', models.DateField()),
                ('next_date', models.DateField()),
                ('task_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.household')),
            ],
            options={
                'indexes': [models.Index(fields=['household', 'is_appliance', 'next_date'], name='maintenance_househo_18fb0d_idx')],
            },
        ),
    ]
